### PR TITLE
Removed some console logging and added more info for image page.

### PR DESCRIPTION
**Pull request by error434**
Anything else I can work on? :)

### CODE REVIEW

**Comment by parthpanchal123** [comment]
@error434 The Build failed with this error 
image

**Comment by error434** [comment]
@parthpanchal123 It should be fixed now. Forgot to update types.ts

**Comment by parthpanchal123** [comment]
@error434 Would you like to take up #20 too?

**Comment by parthpanchal123** [comment]
> @parthpanchal123 sure. I'll push a fix in a while. A bit busy rn.

Yeah yeah no problem at all :smile:

**Comment by error434** [comment]
@parthpanchal123 is that placeholder and implementation fine enough?

**Comment by parthpanchal123** [comment]
The Alignment looks a bit odd on smaller devices 

image

The test should be centred instead of left-aligned .

**Comment by error434** [comment]
@parthpanchal123 Try now. It should be centered.

**Comment by parthpanchal123** [comment]
For Iphone 5/SE , 

image

**Comment by error434** [comment]
@parthpanchal123 try now. God css is so bad.

**Comment by parthpanchal123** [comment]
@error434 I agree , CSS is tough but you got this one :smile: :100: . Thanks for the PR :partying_face:

**Pull request merged**
